version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pgsql12345
      # POSTGRES_DB: rails7_sogou_demo_development 
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    network_mode: default

  # redis:
  #   image: bitnami/redis:latest
  #   environment:
  #     REDIS_PASSWORD: Redis12345 
  #   ports:
  #     - 6379:6379
  #   network_mode: default
